### ISSUE TITLE
Refactor styled-components

### ISSUE THREAD

**Issue by eefborromeo** [eefborromeo/banking-app#41]
Create separate folder and files for styles

**Comment by superspike7** [comment]
I think I'll close this one because it's not that important to our code.

I thought sir Jao suggested that separating styled components is an improvement to our code, but what he meant was that it was to make coding with vim(the text editor that I used) much more easier. 

But I don't think it's necessary for my case because I am also comfortable naman na nasa isang file na yung styles natin.
